### ISSUE TITLE
Missed Words on Knoword

### ISSUE THREAD

**Issue by Dave717** [knoword/support#2]
I cannot see my missed words on Knoword. I have  premium sub, I have tried it on both Chrome and Safari with no luckm the Missed words play area simly doesn't respond

**Comment by trevorblades** [comment]
Hey Dave, are you talking about viewing the words that you miss in a game? They should normally appear on the left side of the screen after and during the game. The list on the game-end screen is scrollable, while the list shown **during** the game is not. I'm attaching screenshots for reference:

![Screen Shot 2019-05-14 at 11 15 43 AM](https://user-images.githubusercontent.com/1216917/57722782-17beb400-763c-11e9-90b7-67b32ae274a1.png)

![Screen Shot 2019-05-14 at 11 20 34 AM](https://user-images.githubusercontent.com/1216917/57722867-4472cb80-763c-11e9-967c-9c314e31909d.png)
